// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class Contratos
{
    public int IdContrato { get; set; }

    public int EmpleadoId { get; set; }

    public int TipoId { get; set; }

    public DateOnly FechaInicio { get; set; }

    public DateOnly? FechaFin { get; set; }

    public decimal Salario { get; set; }

    public string Estado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? HorasJornada { get; set; }

}