// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Infraestructura.AccesoDatos;

public partial class Contratos
{
    public int IdContrato { get; set; }

    public int EmpleadoId { get; set; }

    public int TipoId { get; set; }

    public DateOnly FechaInicio { get; set; }

    public TimeOnly? JornadaHoraInicio { get; set; }

    public TimeOnly? JornadaHoraFin { get; set; }

    public decimal Salario { get; set; }

    public string Estado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

}