// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class Parametros
{
    public int IdParametro { get; set; }

    public string Clave { get; set; }

    public string Valor { get; set; }

    public string Descripcion { get; set; }
}