// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization;

namespace Infraestructura.AccesoDatos;

public partial class SaldoVacaciones
{
    public int Id { get; set; }

    public int IdEmpleado { get; set; }

    public decimal DiasAcumulados { get; set; }

    public DateOnly? FechaUltimaAsignacion { get; set; }

    public decimal DiasUsadosAnioActual { get; set; }

    public int AnioActual { get; set; }
    [JsonIgnore]
    public virtual Empleados IdEmpleadoNavigation { get; set; }
}