// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class Usuarios
{
    public int IdUsuario { get; set; }

    public string Nombre { get; set; }

    public string Cedula { get; set; }

    public byte[] Contraseña { get; set; }

    public string Rol { get; set; }

    public DateTime? FechaRegistro { get; set; }
}