// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class AprobacionVacaciones
{
    public int IdAprobacion { get; set; }

    public int SolicitudId { get; set; }

    public DateTime FechaAprobacion { get; set; }

    public string UsuarioAprobador { get; set; }
 
}