// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class Asistencias
{
    public int IdAsistencia { get; set; }

    public int EmpleadoId { get; set; }

    public DateOnly Fecha { get; set; }

    public TimeOnly? HoraEntrada { get; set; }

    public TimeOnly? HoraSalida { get; set; }

    public bool? Estado { get; set; }

    public TimeOnly? HoraInicioAlmuerzo { get; set; }

    public TimeOnly? HoaFinAlmuerzo { get; set; }

}