// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class Bonificaciones
{
    public int IdBonificacion { get; set; }

    public int EmpleadoId { get; set; }

    public string Tipo { get; set; }

    public string Descripcion { get; set; }

    public decimal Monto { get; set; }

    public DateOnly Fecha { get; set; }

}