// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class ContratosDTO
{


    public int IdContrato { get; set; }
    public int EmpleadoId { get; set; }
    public string CedulaEmpleado { get; set; }
    public string NombreCompletoEmpleado { get; set; }
    public string TipoContrato { get; set; }
    public string DescripcionTipoContrato { get; set; }
    public DateOnly? FechaInicio { get; set; }
    public TimeOnly? JornadaHoraInicio { get; set; }

    public TimeOnly? JornadaHoraFin { get; set; }

    public decimal Salario { get; set; }
    public DateTime FechaCreacion { get; set; }

    public DateTime FechaModificacion { get; set; }
    public string Estado { get; set; }


}