// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class ContratosTipo
{
    public int IdTipo { get; set; }

    public string Jornada { get; set; }

    public string Nombre { get; set; }

    public int? HorasJornada { get; set; } //?

}