// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class EmpleadosVacacionesTotales
{
    public int EmpleadoId { get; set; }

    public int DiasOtorgados { get; set; }

    public int DiasUsados { get; set; } // Total de días de vacaciones que el empleado ha utilizado
   
}