// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class Empleados
{
    public int IdEmpleado { get; set; }

    public int PuestoId { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public string Cedula { get; set; }

    public string Correo { get; set; }

    public DateOnly FechaNacimiento { get; set; }

    public string Genero { get; set; }

    public string Telefono { get; set; }

    public DateOnly FechaIngreso { get; set; }

    public bool Estado { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }
   
}