// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class Inasistencias
{
    public int IdInasistencia { get; set; }

    public int EmpleadoId { get; set; }

    public int LicenciaId { get; set; }

    public DateOnly Fecha { get; set; }

    public int DiasContados { get; set; }

    public bool? Estado { get; set; }

}