// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class Nominas
{
    public int IdNomina { get; set; }

    public int EmpleadoId { get; set; }

    public byte Mes { get; set; }

    public short Anio { get; set; }

    public decimal SalarioBase { get; set; }

    public decimal Bonificaciones { get; set; }

    public decimal Descuentos { get; set; }

    public DateOnly FechaEmision { get; set; }

  
}