// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class Puestos
{
    public int? IdPuesto { get; set; }

    public string Nombre { get; set; }

    public decimal SalarioBase { get; set; }

    public bool? Estado { get; set; }

}