// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace Infraestructura.AccesoDatos;

public partial class SolicitudVacaciones
{
    public int IdSolicitud { get; set; }

    public int EmpleadoId { get; set; }

    public DateOnly FechaInicio { get; set; }

    public DateOnly FechaFin { get; set; }

    public int DiasSolicitados { get; set; }

    public string Estado { get; set; }

    public DateTime FechaCreacion { get; set; }

    
}